using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using GB_Payroll_System.Data;
using GB_Payroll_System.Models;

namespace GB_Payroll_System.Views
{
    // Simple label+amount pair for the earnings / deductions lists
    public record PayslipLineItem(string Label, decimal Amount);

    public partial class PayslipWindow : Window
    {
        private readonly PayrollRunRow  _row;
        private readonly PayrollPeriod  _period;

        public PayslipWindow(PayrollRunRow row, PayrollPeriod period)
        {
            InitializeComponent();
            _row    = row;
            _period = period;
            PopulatePayslip();
        }

        private void PopulatePayslip()
        {
            // Header
            TxtPeriodHeader.Text = $"Pay Period: {_period.StartDate:MMMM dd} – {_period.EndDate:MMMM dd, yyyy}   |   Payout Date: {_period.PayoutDate:MMMM dd, yyyy}";

            // Employee info
            TxtEmpName.Text  = _row.FullName;
            TxtCode.Text     = _row.EmployeeCode;
            TxtDept.Text     = _row.Department;
            TxtPosition.Text = _row.Position;

            // Earnings lines
            var earnings = new List<PayslipLineItem>();
            earnings.Add(new("Basic Pay", _row.BasicPay));
            if (_row.PakyawPay    > 0) earnings.Add(new("Pakyawan / Piece-Rate Pay",  _row.PakyawPay));
            if (_row.OvertimePay  > 0) earnings.Add(new("Overtime Pay (125%)",         _row.OvertimePay));
            if (_row.NightDiffPay > 0) earnings.Add(new("Night Differential (10%)",    _row.NightDiffPay));
            if (_row.HolidayPay   > 0) earnings.Add(new("Holiday Pay",                 _row.HolidayPay));
            if (_row.Allowances   > 0) earnings.Add(new("Allowances",                  _row.Allowances));
            EarningsItems.ItemsSource = earnings;
            TxtGross.Text    = $"₱{_row.GrossPay:N2}";

            // Deductions lines
            var deductions = new List<PayslipLineItem>();
            if (_row.TardinessDeduction > 0) deductions.Add(new("Tardiness / Late Deduction",   _row.TardinessDeduction));
            if (_row.UndertimeDeduction > 0) deductions.Add(new("Undertime Deduction",          _row.UndertimeDeduction));
            if (_row.AbsenceDeduction   > 0) deductions.Add(new("Absence Deduction",            _row.AbsenceDeduction));
            deductions.Add(new("SSS Contribution (Employee)",                                     _row.SssEmployee));
            deductions.Add(new("PhilHealth Premium (Employee)",                                   _row.PhilHealthEmployee));
            deductions.Add(new("Pag-IBIG / HDMF (Employee)",                                     _row.PagIbigEmployee));
            if (_row.WithholdingTax > 0) deductions.Add(new("BIR Withholding Tax (TRAIN Law)",  _row.WithholdingTax));
            if (_row.OtherDeductions > 0) deductions.Add(new("Other Deductions",                 _row.OtherDeductions));
            DeductionItems.ItemsSource = deductions;
            TxtTotalDed.Text = $"₱{_row.TotalDeductions:N2}";

            // Net Pay
            TxtNetPay.Text  = $"₱{_row.NetPay:N2}";

            // Employer contributions
            TxtSssEr.Text = $"₱{_row.SssEmployer:N2}";
            TxtPhEr.Text  = $"₱{_row.PhilHealthEmployer:N2}";
            TxtPiEr.Text  = $"₱{_row.PagIbigEmployer:N2}";

            // Footer
            TxtFooterNote.Text   = $"This payslip was generated by Genetian Payroll System on {DateTime.Now:MMMM dd, yyyy hh:mm tt}";
            TxtPayslipNote.Text  = $"Period: {_period.PeriodCode}   |   Employee: {_row.EmployeeCode}   |   Net Pay: ₱{_row.NetPay:N2}";
        }

        private void BtnPrint_Click(object sender, RoutedEventArgs e)
        {
            var printDialog = new PrintDialog();
            if (printDialog.ShowDialog() != true) return;

            // Render the payslip document area to the printer
            var visual = PayslipDocument;
            printDialog.PrintVisual(visual, $"Payslip – {_row.EmployeeCode} – {_period.PeriodCode}");
        }

        private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();
    }
}
